ezjof/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path ('', include('loginapp.urls')),
    path ('', include('joffeedapp.urls')),
    path ('admin/', admin.site.urls),
]

joffeedapp/models.py
from asyncio.windows_events import NULL
from django.db import models

from loginapp.models import Account, Department

class JOF(models.Model):

    IS_PENDING = 1
    IN_PROGRESS = 2
    NOT_TAKEN = 3
    IS_COMPLETED = 4

    JOF_STATUS_CHOICES = (
        (IS_PENDING, 'Is Pending'),
        (IN_PROGRESS, 'In Progress'),
        (NOT_TAKEN, 'Not Taken'),
        (IS_COMPLETED, 'Is Completed'),
    )

    MP3 = 1
    MP4 = 2
    PNG = 3
    GIF = 4
    PDF = 5
    DOCX = 6
    OTHER = 7    

    JOF_TYPE_CHOICES = (
        (MP3, 'Music/Audio'),
        (MP4, 'Video'),
        (PNG, 'Picture'),
        (GIF, 'GIF'),
        (PDF, 'PDF'),
        (DOCX, 'Word Document'),
        (OTHER, 'Other'),
    )
    
    status = models.IntegerField(choices=JOF_STATUS_CHOICES, default=NOT_TAKEN)
    isrush = models.BooleanField(default=False)
    name = models.CharField(max_length=100, default='')
    description = models.CharField(max_length=500, default='')
    date = models.DateField()
    pegs = models.URLField(null=True, blank=True, default='')
    summary = models.TextField(max_length=500, default='')
    type = models.IntegerField(choices=JOF_TYPE_CHOICES, default=OTHER)
    spiel = models.TextField(max_length=2200, default='')
    client = models.ForeignKey(Account, related_name='Client', on_delete=models.CASCADE, default=NULL)
    artist = models.ForeignKey(Account, related_name='Artist', on_delete=models.CASCADE, default=NULL, blank=True, null=True)
    department = models.ForeignKey(Department, related_name='Department', on_delete=models.CASCADE, default=NULL)
    objects = models.Manager()  
          
class Draft(models.Model):
    jof = models.ForeignKey(JOF, on_delete=models.CASCADE, default=NULL)
    spiel = models.TextField(max_length=2200, default='')
    file = models.FileField(null=True, blank=True, default='')
    dnum = models.IntegerField()
    objects = models.Manager()

class Comment(models.Model):
    draft = models.ForeignKey(Draft, on_delete=models.CASCADE, default=NULL)
    commenter = models.ForeignKey(Account, on_delete=models.CASCADE, default=NULL)
    date = models.DateField()
    content = models.TextField(max_length=500)
    objects = models.Manager()

# Create your models here.

loginapp/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    dname = models.CharField(max_length=100, default='')
    objects = models.Manager()

class Account(models.Model):
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=20)
    name = models.CharField(max_length=100,  default='')
    type = models.CharField(max_length=10, default='')
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True)
    isHead = models.BooleanField(default=False)
    objects = models.Manager()

templates/joffeed/JOFFeed.html
<!-- View for: Artist only -->

{% extends 'base.html' %}
{% load static %}

{% block title %}JOF Feed{% endblock %}
{% block heading %}JOF Feed{% endblock %}

{% block content %}
{% endblock content%}

templates/joffeed/JOFfeed.html
<!-- View for: Artist and Head Artist Only -->

{% extends 'base.html' %}
{% load static %}

{% block title %}JOF Feed{% endblock %}
{% block heading %}<div class="spacer"></div>JOF Feed{% endblock %}

{% block content %}

<div class="flex-cards">
    {% for jof in jofs %}

        {% if jof.status != 4 %}
        <div class="card">
            <h2> {{jof.name}} </h2>
            {% if jof.isrush %}
            <p class="med">Rush | Blast Date: {{jof.date}}</p>
            {% else %}
            <p class="med">Standard | Blast Date: {{jof.date}}</p>
            {% endif %}
            {% if account.type == 'Artist' %}
            <p class="med"> Department: {{jof.client.department.dname}}  </p>
            {% endif %}
            <div class="btn-flex">
                <a href="{% url 'joftracker' jof.pk %}"><button class="btn btn-half secondary">View</button></a>
                <a href="{% url 'jofaccept' jof.pk%}"><button class="btn btn-half primary">Accept</button></a>
            </div>
        </div> 
        {% endif %}
        
    {% endfor %}
</div>

{% endblock content%}

templates/joffeed/JOFtracker.html
<!-- View for: All -->

{% extends 'base.html' %}
{% load static %}

{% block prehead %}
    <a href="{{request.META.HTTP_REFERER|escape}}" class="flex-btn" style="width: 71px; margin: 27px 0px;"><img src="{% static 'images/icons/LeftArrow.svg' %}"> Back</a>

    {% if jof.status == 1 %}
    <span class="chip semibold bginfo500 margmain"> Pending approval </span>
    {% elif jof.status == 2 %}
    <span class="chip semibold bgwarn500 margmain"> In progress </span>
    {% elif jof.status == 3 %}
    <span class="chip semibold bgerror500 margmain"> Not taken </span>
    {% elif jof.status == 4 %}
    <span class="chip semibold bgsucc600 margmain"> Completed </span>
    {% endif %}

{% endblock %}


{% block title %}{{jof.name}}{% endblock %}
{% block heading %}{{jof.name}}{% endblock %}

{% block content %}

{% if jof.isrush %}
<p class="reg med dgray100">Rush | Blast Date: {{jof.date}}</p>
{% else %}
<p class="reg med dgray100">Standard | Blast Date: {{jof.date}}</p>
{% endif %}

<p class="reg">{{jof.summary|linebreaks}}</p>

{% if jof.status != 4 %}
<h2>Specifications</h2>
<p class="reg med dgray100">Deliverable Type: {{jof.get_type_display}}</p>
<p class="reg med dgray100">Deliverable Pegs: <a href="{{jof.pegs}}">{{jof.pegs}}</a></p>
<p class="reg">{{jof.description|linebreaks}}</p>
{% endif %}

{% if jof.status == 3 %}
    <h2>Spiel</h2>
    {% if jof.spiel %}
    <p class="reg">{{jof.spiel|linebreaks}}</p>
    {% else %}
    <p class="reg error600">No spiel was provided by the client.</p>
    {% endif %}

    {% if account.type == 'Artist' %}
    <a href="{% url 'jofaccept' jof.pk%}"><button class="btn btn-flex primary margmain" style="margin-top: 32px;">Accept</button></a>
    {% endif %}
    
{% else %}
    {% if account == jof.client and drafts.count > 0 and jof.status != 4 %}
    <a href="{% url 'joffinish' jof.pk %}"><button class="btn btn-flex primary" style="margin-top: 16px;">Approve Deliverable</button></a>
    {%endif%}

    {%if jof.status == 4%}
    <div class="fieldrow-flex" style="gap: 16px; margin-bottom: 0px;">
        <a id="downloadbutton" href="" download="final"><button class="btn btn-flex primary">Download Pub</button></a>
        <button id="copybutton" name="" class="btn btn-flex primary" onclick="copySpiel()">Copy Spiel</button>
    </div>
    {%endif%}

    <!-- Draft Tabs -->
    {% if drafts.count > 0 %}
        <div id="drafts" class="margmain">
            <div class="tab">
                {%for draft in drafts%}
                    <button class="tabbutton sm semibold" onclick="showDraft(event, 'draft{{draft.dnum}}', 'comments{{draft.dnum}}')" id="tabbutton{{draft.dnum}}">Draft #{{draft.dnum}}</button>
                {%endfor%}
            </div>
            {%for draft in drafts%}
                {%if draft.dnum != drafts.count %}
                    <script>
                        var div = document.createElement("div");
                        var spiel = document.createElement("p");
                        spiel.style.width = "648px";
                        spiel.style.wordBreak = "break-word";
                        spiel.style.whiteSpace = "pre-wrap";
                        spiel.innerHTML = `{{draft.spiel}}`;
                        
                        
                        var img = document.createElement('img');
                        img.className+=" pub";
                        img.src = "{{draft.file.url}}";
                        img.alt = "{{draft.file.url}}";
                        div.id = "draft{{draft.dnum}}"
                        div.append(img, spiel);
                        div.className+=" draftbox deliv";
                        div.style.display = "none";
                        
                        document.getElementById("drafts").append(div);
                    </script>

                {%elif draft.dnum == drafts.count %}
                <script>

                    var div = document.createElement("div");
                    var spiel = document.createElement("p");
                    spiel.style.width = "648px";
                    spiel.style.wordBreak = "break-word";
                    spiel.style.whiteSpace = "pre-wrap";
                    spiel.innerHTML = `{{draft.spiel}}`;
            
                    spiel.id = "finalspiel"
                    
                    var img = document.createElement('img');
                    img.className+=" pub";
                    img.src = "{{draft.file.url}}";
                    div.id = "draft{{draft.dnum}}"
                    div.append(img, spiel);
                    div.className+=" draftbox deliv";
                    div.style.display = "none";
                    
                    document.getElementById("drafts").append(div);

                    document.getElementById("downloadbutton").href = "{{draft.file.url}}";
                </script>
                {%endif%}
            {%endfor%}
        </div>
    {% endif %}

    <!-- Upload -->
    {% if account == jof.artist and drafts.count < 3 and jof.status != 4 %}
    <div id="newdraftbox" class="draftbox margmain" style="display: none">
        <h2>Upload New Draft</h2>
        <form class="fieldcol-flex" method="post" action="{% url 'draftupload' jof.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="field-flex pub">
                <input name="fileinput" type="file" id="id_file" />
            </div>
            <div class="field-flex">
                <label class="label" for="id_spiel">Spiel</label>
                <textarea class="textarea" name="spielinput" style="width: 100%;" id="id_spiel"></textarea>
            </div>
            <input class="btn btn-flex primary" type="submit" name="submit" value="Submit Draft"/>
        </form>
    </div>
    <button class="btn btn-flex primary margmain" style="margin-top: 24px;" onclick="showDraft(event, 'newdraftbox', null)" id="uploadButton">Upload New Draft</button>
    {%endif%}

    <!-- Comments -->
    {%for draft in drafts%}
        <div id="comments{{draft.dnum}}" class="commentbox" style="display:none">
            <h2 style="margin-top: 32px;">Comments</h2>
            {% if comments %}
                <div class="commentset">
                    {% for comment in comments %}
                        {%if comment.draft == draft%}
                            <div class="comment">
                                <p class="reg semibold btn-flex">{{comment.commenter.name}} <span class="xs med dgray100">{{comment.date}}</span></p>
                                <p class="reg" style="word-wrap: break-word;">{{comment.content|linebreaks}}</p>
                            </div>
                        {%endif%}
                    {% endfor %}
                </div>
            {% endif %}
            {% if jof.status != 4 %}
            <form method="post" action="{% url 'commentadd' draft.pk %}">
                {% csrf_token %}
                <div class="field-flex" style="margin-top: 32px">
                    <textarea class="textarea" style="width: 100%;" name="commentinput" placeholder="Add a comment..." id="id_comment"></textarea>
                </div>
                <input class="btn btn-flex primary" style="margin: 24px 0px;" type="submit" name="submit" value="Post Comment"/>
            </form>
            {% endif %}
        </div>
        
    {%endfor%}
{% endif %}

<!-- Set default clicked tab -->
{% if drafts.count == 1 %}
    <script>
        document.body.onload = function()
        {
            document.getElementById("tabbutton1").click();
        }
    </script>
{% elif drafts.count == 2 %}
    <script>
        document.body.onload = function()
        {    
            document.getElementById("tabbutton2").click();
        }
    </script>
{% elif drafts.count == 3 %}
    <script>
        document.body.onload = function()
        {    
            document.getElementById("tabbutton3").click();
        }
    </script>
{% endif %}

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/trackerfunc_script.js' %}"></script>
{% endblock %}

templates/joffeed/archive.html
<!-- View for: All roles -->

{% extends 'base.html' %}
{% load static %}

{% block title %}Archive{% endblock %}
{% block heading %}Archive{% endblock %}

{% block content %}
{% endblock content%}

templates/joffeed/archivedJOFs.html
<!-- View for: All roles -->

{% extends 'base.html' %}
{% load static %}

{% block title %}Archived JOFs{% endblock %}
{% block heading %}<div class="spacer"></div>Archived JOFs{% endblock %}

{% block content %}


<form style="display: inline-block; margin: 24px -8px; vertical-align: middle;" method="GET" action="" >
    <input class="textfield" style="display:inline; width: 283px; height: 32px;" type="search" name="search"> 
    <button class="btn flex-btn secondary" style="display:inline; width: 32px; height: 32px;" type="submit"><img src="{% static 'images/icons/Search.svg' %}"></button>
</form>

{% if account.type == 'Client'%}
    <a href="{% url 'jofcreate'%}"><button class="btn flex-btn btn-half primary" style="float: right; margin: 24px 0px;">
        <img src="{% static 'images/icons/Plus.svg' %}"> New JOF</button>
    </a>
{%endif%}



<div class="flex-cards">
    {% for jof in jofs %}
    {% if jof.status == 4 %}
        <div class="card">
            <h2 class="prim700 semibold"> {{jof.name}} </h2>
            <p class="med"> Blast Date: {{jof.date}}  </p>
            {% if account.type == 'Artist' %}
            <p class="med"> Department: {{jof.client.department.dname}}  </p>
            {% endif %}
            <span class="chip semibold bgsucc600"> Completed </span>
            <a href="{% url 'joftracker' jof.pk %}"><button class="btn btn-full primary">View</button></a>
        </div> 
    {% endif %}
    {% endfor %}
</div>


{% endblock content%}

templates/joffeed/createJOF.html
<!-- View for: Clients Only -->

{% extends 'base.html' %}
{% load static %}

{% block title %}Create New JOF{% endblock %}
{% block heading %}<div class="spacer"></div>Create New JOF{% endblock %}

{% block content %}
    <form method = "post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div style="display:inline-block;">
            {{ form.isrush.errors }}
            {{ form.isrush }}
            <label class="sm semibold" for="{{ form.isrush.id_for_label }}">Rush?</label>
        </div>
        <div class="fieldrow-flex">
            <div class="field-flex">
                {{ form.name.errors }}
                <label class="label" for="{{ form.name.id_for_label }}">Name</label>
                <input type="text" name="name" class="textfield" style="margin: 0px;" maxlength="100" required id="id_name">
            </div>
            <div class="field-flex">
                {{ form.date.errors }}
                <label class="label" for="{{ form.date.id_for_label }}">Blast Date (YYYY-MM-DD) </label>
                <input type="text" name="date" class="textfield" style="margin: 0px;" required id="id_date">
            </div>
        </div>
        <div class="field-flex" style="margin: 24px 0px 64px;">
            {{ form.summary.errors }}
            <label class="label" for="{{ form.summary.id_for_label }}">Purpose</label>
            <textarea name="summary" class="textarea" maxlength="500" required id="id_summary"></textarea>
        </div>

        <h2>Specifications</h2>
        <div class="fieldrow-flex">
            <div>
                {{ form.type.errors }}
                <label class="label" style="margin: -4px 0px" for="{{ form.type.id_for_label }}">Type</label>
                {{ form.type }}
            </div>
            <div class="field-flex">
                {{ form.pegs.errors }}
                <label class="label" for="{{ form.pegs.id_for_label }}">Link to Pegs</label>
                <input type="url" name="pegs" class="textfield" style="margin: 0px;" maxlength="200" required id="id_pegs">
            </div>
        </div>
        <div class="field-flex" style="margin: 24px 0px;">
            {{ form.description.errors }}
            <label class="label" for="{{ form.description.id_for_label }}">Contents</label>
            <textarea type="text" name="description" class="textarea" maxlength="500" required id="id_description"></textarea>
        </div>
        <div class="field-flex" style="margin: 24px 0px 48px;">
            {{ form.spiel.errors }}
            <label class="label" for="{{ form.spiel.id_for_label }}">Spiel (Leave blank if artist will provide)</label>
            <textarea type="text" name="spiel" class="textarea" maxlength="2200" id="id_spiel"></textarea>
        </div>
            <input class="btn btn-half primary" style="margin-bottom: 64px;" type="submit" value="Submit"></button>
    </form>
{% endblock content%}

templates/joffeed/currentJOFs.html
<!-- View for: All roles -->

{% extends 'base.html' %}
{% load static %}

{% block title %}Current JOFs{% endblock %}
{% block heading %}<div class="spacer"></div>Current JOFs{% endblock %}

{% block content %}

<form style="display: inline-block; margin: 24px -8px; vertical-align: middle;" method="GET" action="" >
    <input class="textfield" style="display:inline; width: 283px; height: 32px;" type="search" name="search">
    <button class="btn flex-btn secondary" style="display:inline; width: 32px; height: 32px;" type="submit"><img src="{% static 'images/icons/Search.svg' %}"></button>
</form>
{% if account.type == 'Client'%}
    <a href="{% url 'jofcreate'%}"><button class="btn flex-btn btn-half primary" style="float: right; margin: 24px 0px;">
        <img src="{% static 'images/icons/Plus.svg' %}"> New JOF</button>
    </a>
{%endif%}

<div class="flex-cards">
    {% for jof in jofs %}
        {% if jof.status != 4 %}
            <div class="card">
                <h2 class="prim700 semibold"> {{jof.name}} </h2>
                {% if jof.isrush %}
                <p class="med">Rush | Blast Date: {{jof.date}}</p>
                {% else %}
                <p class="med">Standard | Blast Date: {{jof.date}}</p>
                {% endif %}
                {% if account.type == 'Artist' %}
                <p class="med"> Department: {{jof.department.dname}}  </p>
                {% endif %}
                {% if jof.status == 1 %}
                <span class="chip semibold bginfo500"> Pending approval </span>
                {% endif %}
                {% if jof.status == 2 %}
                <span class="chip semibold bgwarn500"> In progress </span>
                {% endif %}
                {% if jof.status == 3 %}
                <span class="chip semibold bgerror500"> Not taken </span>
                {% endif %}
                <a href="{% url 'joftracker' jof.pk %}"><button class="btn btn-full primary">View</button></a>
            </div> 
        {% endif %}
    {% endfor %}
</div>
{% endblock content%}

templates/joffeed/rushJOFs.html
<!-- View for: Head Artist only -->

{% extends 'base.html' %}
{% load static %}

{% block title %}Rush JOFs{% endblock %}
{% block heading %}<div class="spacer"></div>Rush JOFs{% endblock %}

{% block content %}

<div class="flex-cards">
    {% for jof in jofs %}

        {% if jof.status != 4 and jof.isrush %}
        <div class="card">
            <h2> {{jof.name}} </h2>
            <p class="med"> Blast Date: {{jof.date}}  </p>
            {% if account.type == 'Artist' %}
            <p class="med"> Department: {{jof.department.dname}}  </p>
            {% endif %}
            <div class="btn-flex">
                <a href="{% url 'jofview' jof.pk %}"><button class="btn btn-half secondary">View</button></a>
                <a href="{% url 'jofapprove' jof.pk %}"><button class="btn btn-half primary">Approve</button></a>
            </div>
        </div> 
        {% endif %}
        
    {% endfor %}
</div>

{% endblock content%}